### ISSUE TITLE
State?

### ISSUE THREAD

**Issue by joakim** [jasonsbarr/pratt-generator#1]
Had a look at `test.js` and must say it looks pretty nice! What's the state of this thing? Could I use it to parse something like JSON?

**Comment by jasonsbarr** [comment]
I'm not sure, but possibly. The only thing I know for sure isn't working right is expressions in parentheses (the operation defined starting at line 192 of test.js). I'm pretty sure I know how to fix it - I just haven't had time because work has been busy.

**Comment by jasonsbarr** [comment]
Honestly I'd like to come back to this project and test it more rigorously, see if I can make it useful.

**Comment by joakim** [comment]
Thanks for the quick reply! Cool. I'll have a look at some other Pratt parsers first before I decide whether to hand craft or try building upon this. So don't sweat it for my sake :)

**Comment by jasonsbarr** [comment]
If you look at the parser for the language I'm currently working on, you'll see I've adapted the same table-driven approach for it. It's not generated on the fly, I'm coding it by hand, but still using Pratt's technique for parsing expressions. I do still store the precedence and associativity of each operation in a table though, so that at least is still the same.

https://github.com/jasonsbarr/chopin

**Comment by jasonsbarr** [comment]
The language is FAR from ready for prime time; I just started working on it a couple of weeks ago and I work all day so I don't get to work on it as much as I'd like. It's my first attempt at a statically typed language, using bidirectional type checking with some degree of inference.

**Comment by joakim** [comment]
Nice! Sounds like a language I'd be interested in having a closer look at. From what I can see, you've already come a long way.

I've also designed a compile-to-JavaScript language, [kesh](https://github.com/kesh-lang/kesh/wiki/Documentation). Actually, compile-to-TypeScript's AST, if that's possible. The idea is to piggyback on TypeScript's compiler and get a lot of things for free. I don't really have the time to work on it, but I'd like to at least have a parser for my data notation format, [na](https://github.com/kesh-lang/na).
